# Generated by Django 6.0.1 on 2026-01-20 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
        migrations.CreateModel(
            name="ParentVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(default="", max_length=18, verbose_name="身份证"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("W", "待审核"),
                            ("P", "审核通过"),
                            ("F", "审核不通过"),
                        ],
                        default="W",
                        max_length=1,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
