# Generated by Django 6.0.1 on 2026-01-20 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_user_type_parentverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentverification",
            name="id",
        ),
        migrations.AlterField(
            model_name="parentverification",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="parent",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
