# Generated by Django 6.0.1 on 2026-01-22 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_parentverification_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorVerification',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tutor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('id_card', models.CharField(default='', max_length=18, verbose_name='身份证')),
                ('student_card', models.ImageField(upload_to='verify/tutor/student_card/', verbose_name='学生证')),
                ('college_entrance_score', models.IntegerField(default=0, verbose_name='高考成绩')),
                ('teacher_qualification_certificate', models.ImageField(blank=True, null=True, upload_to='verify/tutor/teacher_qualification_certificate/', verbose_name='教师资格证')),
                ('status', models.CharField(choices=[('W', '待审核'), ('P', '审核通过'), ('F', '审核不通过')], default='W', max_length=1, verbose_name='审核状态')),
            ],
        ),
    ]
