# Generated by Django 6.0.1 on 2026-01-26 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(default='', max_length=20, verbose_name='学员姓名')),
                ('student_age', models.IntegerField(default=0, verbose_name='学员年龄')),
                ('student_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='M', max_length=1, verbose_name='学员性别')),
                ('student_grade', models.CharField(choices=[('P1', '一年级'), ('P2', '二年级'), ('P3', '三年级'), ('P4', '四年级'), ('P5', '五年级'), ('P6', '六年级'), ('J1', '初一'), ('J2', '初二'), ('J3', '初三'), ('S1', '高一'), ('S2', '高二'), ('S3', '高三')], default='P1', max_length=2, verbose_name='学员年级')),
                ('subject', models.CharField(choices=[('CHI', '语文'), ('MAT', '数学'), ('ENG', '英语'), ('PHI', '物理'), ('CHE', '化学'), ('BIO', '生物'), ('POL', '政治'), ('HIS', '历史'), ('GEO', '地理')], default='CHI', max_length=3, verbose_name='辅导科目')),
                ('experienced', models.BooleanField(default=False, verbose_name='是否有基础')),
                ('method', models.CharField(choices=[('T', '学员上门'), ('S', '家教上门'), ('O', '线上辅导')], default='O', max_length=2, verbose_name='辅导方式')),
                ('tutor_gender', models.CharField(choices=[('M', '男'), ('F', '女'), ('U', '未知')], default='M', max_length=1, verbose_name='家教性别')),
                ('lesson_date', models.CharField(default='', max_length=200, verbose_name='辅导日期')),
                ('lesson_time', models.CharField(default='', max_length=200, verbose_name='辅导时间')),
                ('payment_type', models.CharField(choices=[('D', '按天收费'), ('H', '按小时收费'), ('C', '面议')], default='C', max_length=1, verbose_name='支付方式')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='薪资')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_requests', to=settings.AUTH_USER_MODEL, verbose_name='家长')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=3, verbose_name='评价')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_orders', to=settings.AUTH_USER_MODEL, verbose_name='家教')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='order.request', verbose_name='要求')),
            ],
        ),
    ]
