# Generated by Django 6.0.1 on 2026-01-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='lesson_days',
            field=models.IntegerField(default=0, verbose_name='辅导天数'),
        ),
    ]
